[tool.poetry]
name = "arcbest-api"
version = "0.1.0"
description = ""
authors = ["Leif Jessen <ljessen@perfectscoretiming.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
xmltodict = "^0.13.0"
email-validator = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
